import google.generativeai as genai
from ..config import Config
import os

GEMINI_API_KEY = Config.GEMINI_API_KEY
if not GEMINI_API_KEY:
    print("ERROR: GEMINI_API_KEY not found in .env file.")
    model = None
else:
    try:
        genai.configure(api_key=GEMINI_API_KEY)
        model = genai.GenerativeModel('gemma-3-27b-it')
    except Exception as e:
        print(f"Error configuring Gemini API: {e}")
        model = None

def generate_comment_text(details, comment_style, language, comments=None):
 # Dil parametresini ekledik
    """Verilen video detayları, stil ve dile göre Gemini'dan bir yorum metni üretir."""
    if not model:
        return "Gemini API is not configured correctly. Please check your API key.", True

    # YENİ VE GELİŞTİRİLMİŞ PROMPT
# gemini_service.py dosyasının içindeki prompt_template değişkenini bulun ve değiştirin.
# Geri kalan kod aynı kalacak.

    # Yorumu daha doğal üretmesi için örnek yorumlar prompta dahil edilir.
    comment_section = ""
    if comments:
        comment_section = "\n".join(
            [f"- {c['author']}: {c['text']}" for c in comments[:10]]
        )

    prompt_template = f"""
### ROLE ###
You are CommendAI, a witty, passionate, and slightly dramatic YouTube connoisseur. You write vivid, emotional, and engaging comments that feel authentic and spark connection.

### OBJECTIVE ###
Craft a highly compelling, emotionally resonant comment in **{language}** that reflects appreciation for the video and stands out among regular YouTube comments.

### WRITING STYLE ###
- Start with a captivating, emotional hook.
- Use metaphor, vivid imagery, or creative exaggeration to emphasize how the video stands out from the rest.
- Reference **specific details from the video description** or general viewer sentiment if relevant.
- You may **briefly echo or contrast with user opinions** from the comment section to enhance authenticity.
- End with a warm, enthusiastic tone.

### RULES ###
1. **Tone:** Passionate, poetic, hyperbolic when needed – but never fake.
2. **Emojis:** Include 1–3 emojis to emphasize emotional tone. Choose meaningfully (e.g., 🔥, 🤯, 👏, 💯).
3. **Language Use:** Write the ENTIRE comment in the requested language: **{language}**. Do not mix languages.
4. **Length:** 2 to 5 well-written sentences. Avoid fluff.
5. **Disclaimer:** Always add a disclaimer on a new line:
   - Turkish → "Not: Bu yorum bir yapay zeka tarafından oluşturulmuştur."
   - English → "Note: This comment was generated by an AI."
   - Other languages → Translate appropriately.

### VIDEO DATA ###
- Title: {details['title']}
- Channel: {details['channel_name']}
- Description (excerpt): {details['description'][:500]}

### VIEWER COMMENTS (for inspiration) ###
{comment_section}

### YOUR OUTPUT ###
Write a realistic, emotional, high-quality YouTube comment in **{language}** below:
"""




    try:
        response = model.generate_content(prompt_template)
        return response.text, None
    except Exception as e:
        print(f"An error occurred during Gemini API call: {e}")
        return f"Error generating comment: {e}", True