// Multi-language translations for the entire site interface
export const translations = {
  en: {
    // Header
    siteTitle: "CommendAI",
    authorBy: "by Hasan Arthur Altuntaş",
    homeNav: "Home",
    
    // Main Title
    pageTitle: "CommendAI",
    
    // Status Messages
    statusReady: "Ready to generate new comment.",
    statusGenerating: "🧠 AI is generating comment... Please wait.",
    statusGenerated: "✅ Comment generated successfully! You can send it to YouTube.",
    statusPosting: "🚀 Posting comment to YouTube...",
    statusPosted: "✅ Comment posted! Ready for new video.",
    statusError: "❌ Comment could not be generated",
    statusPostError: "❌ Comment could not be posted",
    statusCopied: "📋 Copied to clipboard!",
    statusHistoryLoaded: "📋 Comment loaded from history. Ready to post.",
    
    // Form Labels
    formVideoUrl: "YouTube Video URL",
    formVideoUrlPlaceholder: "https://www.youtube.com/watch?v=...",
    formCommentLanguage: "Comment Language",
    formGenerateButton: "Generate Comment",
    formGenerating: "Generating...",
    
    // Result Area
    resultTitle: "Generated Comment",
    resultReadonlyNotice: "This comment is generated by AI and cannot be edited.",
    resultPlaceholder: "Generated comment will appear here...",
    buttonPostToYoutube: "Post to YouTube",
    buttonPosting: "Posting...",
    buttonCopyText: "Copy Text",
    
    // History Panel
    historyTitle: "Comment History",
    historyToggleShow: "Show History",
    historyToggleHide: "Hide History",
    historyUseButton: "Use",
    historyPostedBadge: "Posted",
    historyEmpty: "No comment history yet.",
    
    // Error Messages
    errorUnknown: "An unknown error occurred.",
    errorConnection: "Connection error:",
    errorPostUnknown: "Unknown error occurred while posting comment.",
    errorHistoryLoad: "Comment history could not be loaded.",
    errorDuplicateDetected: "⚠️ Warning: Duplicate video detected",
    errorCannotPost: "🚫 Comment could not be posted!",
    errorAlreadyPosted: "comments have already been posted to this video...",
    errorVideoNotFound: "Video not found or unavailable.",
    errorApiLimit: "API limit exceeded. Please try again later.",
    errorInvalidUrl: "Please enter a valid YouTube URL.",
    
    // Success Messages
    successPosted: "🎉 Comment successfully posted to YouTube!",
    
    // Admin Panel (if exists)
    adminTitle: "Admin Panel",
    adminLogin: "Login",
    adminLogout: "Logout",
    adminUsername: "Username",
    adminPassword: "Password",
    adminLoginError: "Invalid username or password.",
    
    // Languages
    languages: {
      Turkish: "Turkish",
      English: "English", 
      Russian: "Russian",
      Chinese: "Chinese",
      Japanese: "Japanese"
    },
    
    // Language Selector
    selectLanguage: "Select language",
    
    // Accessibility
    ariaLanguageSelector: "Language selector",
    ariaSwitchTo: "Switch to",
    ariaCloseError: "Close error message"
  },
  
  tr: {
    // Header
    siteTitle: "CommendAI",
    authorBy: "Hasan Arthur Altuntaş tarafından",
    homeNav: "Ana Sayfa",
    
    // Main Title  
    pageTitle: "CommendAI",
    
    // Status Messages
    statusReady: "Yeni yorum oluşturmaya hazır.",
    statusGenerating: "🧠 AI yorum oluşturuyor... Lütfen bekleyin.",
    statusGenerated: "✅ Yorum başarıyla oluşturuldu! YouTube'a gönderebilirsiniz.",
    statusPosting: "🚀 Yorum YouTube'a gönderiliyor...",
    statusPosted: "✅ Yorum gönderildi! Yeni video için hazır.",
    statusError: "❌ Yorum oluşturulamadı",
    statusPostError: "❌ Yorum gönderilemedi",
    statusCopied: "📋 Panoya kopyalandı!",
    statusHistoryLoaded: "📋 Geçmişten yorum yüklendi. Gönderime hazır.",
    
    // Form Labels
    formVideoUrl: "YouTube Video URL'si",
    formVideoUrlPlaceholder: "https://www.youtube.com/watch?v=...",
    formCommentLanguage: "Yorum Dili",
    formGenerateButton: "Yorum Oluştur",
    formGenerating: "Oluşturuluyor...",
    
    // Result Area
    resultTitle: "Oluşturulan Yorum",
    resultReadonlyNotice: "Bu yorum AI tarafından oluşturulmuştur ve düzenlenemez.",
    resultPlaceholder: "Oluşturulan yorum burada görünecek...",
    buttonPostToYoutube: "YouTube'a Gönder",
    buttonPosting: "Gönderiliyor...",
    buttonCopyText: "Metni Kopyala",
    
    // History Panel
    historyTitle: "Yorum Geçmişi",
    historyToggleShow: "Geçmişi Göster",
    historyToggleHide: "Geçmişi Gizle",
    historyUseButton: "Kullan",
    historyPostedBadge: "Gönderildi",
    historyEmpty: "Henüz yorum geçmişi yok.",
    
    // Error Messages
    errorUnknown: "Bilinmeyen bir hata oluştu.",
    errorConnection: "Bağlantı hatası:",
    errorPostUnknown: "Yorum gönderilirken bilinmeyen bir hata oluştu.",
    errorHistoryLoad: "Yorum geçmişi yüklenemedi.",
    errorDuplicateDetected: "⚠️ Uyarı: Duplicate video tespit edildi",
    errorCannotPost: "🚫 Yorum gönderilemedi!",
    errorAlreadyPosted: "kez yorum gönderildi bu videoya...",
    errorVideoNotFound: "Video bulunamadı veya erişilemiyor.",
    errorApiLimit: "API limiti aşıldı. Lütfen daha sonra tekrar deneyin.",
    errorInvalidUrl: "Lütfen geçerli bir YouTube URL'si girin.",
    
    // Success Messages
    successPosted: "🎉 Yorum başarıyla YouTube'a gönderildi!",
    
    // Admin Panel
    adminTitle: "Admin Paneli",
    adminLogin: "Giriş Yap",
    adminLogout: "Çıkış Yap",
    adminUsername: "Kullanıcı Adı",
    adminPassword: "Şifre", 
    adminLoginError: "Geçersiz kullanıcı adı veya şifre.",
    
    // Languages
    languages: {
      Turkish: "Türkçe",
      English: "İngilizce",
      Russian: "Rusça", 
      Chinese: "Çince",
      Japanese: "Japonca"
    },
    
    // Language Selector
    selectLanguage: "Dil seçin",
    
    // Accessibility
    ariaLanguageSelector: "Dil seçici",
    ariaSwitchTo: "Şuna geç:",
    ariaCloseError: "Hata mesajını kapat"
  },
  
  ru: {
    // Header
    siteTitle: "CommendAI", 
    authorBy: "от Hasan Arthur Altuntaş",
    homeNav: "Главная",
    
    // Main Title
    pageTitle: "CommendAI",
    
    // Status Messages
    statusReady: "Готов к созданию нового комментария.",
    statusGenerating: "🧠 ИИ создает комментарий... Пожалуйста, подождите.",
    statusGenerated: "✅ Комментарий успешно создан! Вы можете отправить его на YouTube.",
    statusPosting: "🚀 Отправка комментария на YouTube...",
    statusPosted: "✅ Комментарий отправлен! Готов к новому видео.",
    statusError: "❌ Не удалось создать комментарий",
    statusPostError: "❌ Не удалось отправить комментарий",
    statusCopied: "📋 Скопировано в буфер обмена!",
    statusHistoryLoaded: "📋 Комментарий загружен из истории. Готов к отправке.",
    
    // Form Labels
    formVideoUrl: "URL видео YouTube",
    formVideoUrlPlaceholder: "https://www.youtube.com/watch?v=...",
    formCommentLanguage: "Язык комментария",
    formGenerateButton: "Создать комментарий",
    formGenerating: "Создание...",
    
    // Result Area
    resultTitle: "Созданный комментарий",
    resultReadonlyNotice: "Этот комментарий создан ИИ и не может быть отредактирован.",
    resultPlaceholder: "Созданный комментарий появится здесь...",
    buttonPostToYoutube: "Отправить на YouTube",
    buttonPosting: "Отправка...",
    buttonCopyText: "Копировать текст",
    
    // History Panel
    historyTitle: "История комментариев",
    historyToggleShow: "Показать историю",
    historyToggleHide: "Скрыть историю",
    historyUseButton: "Использовать",
    historyPostedBadge: "Отправлено",
    historyEmpty: "История комментариев пуста.",
    
    // Error Messages
    errorUnknown: "Произошла неизвестная ошибка.",
    errorConnection: "Ошибка соединения:",
    errorPostUnknown: "Произошла неизвестная ошибка при отправке комментария.",
    errorHistoryLoad: "Не удалось загрузить историю комментариев.",
    errorDuplicateDetected: "⚠️ Предупреждение: Обнаружено дублированное видео",
    errorCannotPost: "🚫 Не удалось отправить комментарий!",
    errorAlreadyPosted: "комментариев уже отправлено на это видео...",
    errorVideoNotFound: "Видео не найдено или недоступно.",
    errorApiLimit: "Превышен лимит API. Пожалуйста, попробуйте позже.",
    errorInvalidUrl: "Пожалуйста, введите действительный URL YouTube.",
    
    // Success Messages
    successPosted: "🎉 Комментарий успешно отправлен на YouTube!",
    
    // Admin Panel
    adminTitle: "Панель администратора",
    adminLogin: "Войти",
    adminLogout: "Выйти",
    adminUsername: "Имя пользователя",
    adminPassword: "Пароль",
    adminLoginError: "Неверное имя пользователя или пароль.",
    
    // Languages
    languages: {
      Turkish: "Турецкий",
      English: "Английский",
      Russian: "Русский",
      Chinese: "Китайский", 
      Japanese: "Японский"
    },
    
    // Language Selector
    selectLanguage: "Выберите язык",
    
    // Accessibility
    ariaLanguageSelector: "Селектор языка",
    ariaSwitchTo: "Переключиться на",
    ariaCloseError: "Закрыть сообщение об ошибке"
  },
  
  zh: {
    // Header
    siteTitle: "CommendAI",
    authorBy: "由 Hasan Arthur Altuntaş 制作",
    homeNav: "首页",
    
    // Main Title
    pageTitle: "CommendAI",
    
    // Status Messages
    statusReady: "准备生成新评论。",
    statusGenerating: "🧠 AI正在生成评论...请等待。",
    statusGenerated: "✅ 评论生成成功！您可以发送到YouTube。",
    statusPosting: "🚀 正在发送评论到YouTube...",
    statusPosted: "✅ 评论已发送！准备新视频。",
    statusError: "❌ 无法生成评论",
    statusPostError: "❌ 无法发送评论",
    statusCopied: "📋 已复制到剪贴板！",
    statusHistoryLoaded: "📋 从历史记录加载评论。准备发送。",
    
    // Form Labels
    formVideoUrl: "YouTube视频网址",
    formVideoUrlPlaceholder: "https://www.youtube.com/watch?v=...",
    formCommentLanguage: "评论语言",
    formGenerateButton: "生成评论",
    formGenerating: "生成中...",
    
    // Result Area
    resultTitle: "生成的评论",
    resultReadonlyNotice: "此评论由AI生成，无法编辑。",
    resultPlaceholder: "生成的评论将在这里显示...",
    buttonPostToYoutube: "发送到YouTube",
    buttonPosting: "发送中...",
    buttonCopyText: "复制文本",
    
    // History Panel
    historyTitle: "评论历史",
    historyToggleShow: "显示历史",
    historyToggleHide: "隐藏历史",
    historyUseButton: "使用",
    historyPostedBadge: "已发送",
    historyEmpty: "暂无评论历史。",
    
    // Error Messages
    errorUnknown: "发生未知错误。",
    errorConnection: "连接错误：",
    errorPostUnknown: "发送评论时发生未知错误。",
    errorHistoryLoad: "无法加载评论历史。",
    errorDuplicateDetected: "⚠️ 警告：检测到重复视频",
    errorCannotPost: "🚫 无法发送评论！",
    errorAlreadyPosted: "条评论已发送到此视频...",
    errorVideoNotFound: "找不到视频或无法访问。",
    errorApiLimit: "API限制已达到。请稍后再试。",
    errorInvalidUrl: "请输入有效的YouTube网址。",
    
    // Success Messages
    successPosted: "🎉 评论已成功发送到YouTube！",
    
    // Admin Panel
    adminTitle: "管理面板",
    adminLogin: "登录",
    adminLogout: "退出",
    adminUsername: "用户名",
    adminPassword: "密码",
    adminLoginError: "用户名或密码无效。",
    
    // Languages
    languages: {
      Turkish: "土耳其语",
      English: "英语",
      Russian: "俄语",
      Chinese: "中文",
      Japanese: "日语"
    },
    
    // Language Selector
    selectLanguage: "选择语言",
    
    // Accessibility
    ariaLanguageSelector: "语言选择器",
    ariaSwitchTo: "切换到",
    ariaCloseError: "关闭错误消息"
  },
  
  ja: {
    // Header
    siteTitle: "CommendAI",
    authorBy: "Hasan Arthur Altuntaş による",
    homeNav: "ホーム",
    
    // Main Title
    pageTitle: "CommendAI",
    
    // Status Messages
    statusReady: "新しいコメントの生成準備完了。",
    statusGenerating: "🧠 AIがコメントを生成中...お待ちください。",
    statusGenerated: "✅ コメントが正常に生成されました！YouTubeに送信できます。",
    statusPosting: "🚀 YouTubeにコメントを送信中...",
    statusPosted: "✅ コメントが送信されました！新しい動画の準備完了。",
    statusError: "❌ コメントを生成できませんでした",
    statusPostError: "❌ コメントを送信できませんでした",
    statusCopied: "📋 クリップボードにコピーしました！",
    statusHistoryLoaded: "📋 履歴からコメントをロードしました。送信準備完了。",
    
    // Form Labels
    formVideoUrl: "YouTube動画URL",
    formVideoUrlPlaceholder: "https://www.youtube.com/watch?v=...",
    formCommentLanguage: "コメント言語",
    formGenerateButton: "コメント生成",
    formGenerating: "生成中...",
    
    // Result Area
    resultTitle: "生成されたコメント",
    resultReadonlyNotice: "このコメントはAIによって生成されており、編集できません。",
    resultPlaceholder: "生成されたコメントがここに表示されます...",
    buttonPostToYoutube: "YouTubeに投稿",
    buttonPosting: "投稿中...",
    buttonCopyText: "テキストをコピー",
    
    // History Panel
    historyTitle: "コメント履歴",
    historyToggleShow: "履歴を表示",
    historyToggleHide: "履歴を非表示",
    historyUseButton: "使用",
    historyPostedBadge: "投稿済み",
    historyEmpty: "コメント履歴がまだありません。",
    
    // Error Messages
    errorUnknown: "不明なエラーが発生しました。",
    errorConnection: "接続エラー：",
    errorPostUnknown: "コメント送信中に不明なエラーが発生しました。",
    errorHistoryLoad: "コメント履歴を読み込めませんでした。",
    errorDuplicateDetected: "⚠️ 警告：重複動画が検出されました",
    errorCannotPost: "🚫 コメントを送信できませんでした！",
    errorAlreadyPosted: "件のコメントがこの動画に既に投稿されています...",
    errorVideoNotFound: "動画が見つからないか、アクセスできません。",
    errorApiLimit: "API制限に達しました。後でもう一度試してください。",
    errorInvalidUrl: "有効なYouTube URLを入力してください。",
    
    // Success Messages
    successPosted: "🎉 コメントがYouTubeに正常に投稿されました！",
    
    // Admin Panel
    adminTitle: "管理パネル",
    adminLogin: "ログイン",
    adminLogout: "ログアウト",
    adminUsername: "ユーザー名",
    adminPassword: "パスワード",
    adminLoginError: "無効なユーザー名またはパスワードです。",
    
    // Languages
    languages: {
      Turkish: "トルコ語",
      English: "英語",
      Russian: "ロシア語",
      Chinese: "中国語",
      Japanese: "日本語"
    },
    
    // Language Selector
    selectLanguage: "言語を選択",
    
    // Accessibility
    ariaLanguageSelector: "言語セレクター",
    ariaSwitchTo: "切り替え先：",
    ariaCloseError: "エラーメッセージを閉じる"
  }
};

// Helper function to get translation
export const getTranslation = (language, key) => {
  const keys = key.split('.');
  let translation = translations[language];
  
  for (const k of keys) {
    if (translation && translation[k]) {
      translation = translation[k];
    } else {
      // Fallback to English if translation not found
      translation = translations['en'];
      for (const k of keys) {
        if (translation && translation[k]) {
          translation = translation[k];
        } else {
          return key; // Return key if no translation found
        }
      }
      break;
    }
  }
  
  return translation;
};